### ISSUE TITLE
Bash: heredoc and arrays are not correctly covered

### ISSUE THREAD

**Issue by beatussum** [SimonKagstrom/kcov#457]
# Description

In bash, if a heredoc has space between the tag and `<<[-]`, the lines of the string are not covered.

Same thing with arrays if they are not defined oneline.

It occurs also with functions in subshells like:

```bash
foo() (
    echo "bar"
)
```

# Example

![Example](https://github.com/user-attachments/assets/9517238b-bf6a-44a4-bb84-5693550d0d5c)

**Comment by SimonKagstrom** [comment]
Thanks for the clear test!

This, and other bash parsing issues, should really be handled by #145 , but I don't really have any timeframe for that. I mostly (almost only) use kcov for compiled code myself, so the bash support is sort of neglected by me.

**Comment by beatussum** [comment]
Currently, the following has been _fixed_ (it's not perfect and other issues risk to occur):
- [x] code coverage of _heredoc_ having spaces between `<<[-]` and the tag (see e208a4ed2180c70dc94b84faf438ffedbc277765 provided by #459).
- [x] code coverage of subshell functions (see 32c6189c8fd88a164d381fdb77ec6350153923ea provided by #459).
- [ ] code coverage of multiline arrays. As it's explained in [this comment](https://github.com/SimonKagstrom/kcov/pull/459#issuecomment-2261347586), parsing of these arrays seems quiet difficult without a true parser (see #145).

**Comment by SimonKagstrom** [comment]
Thanks a lot for these! I'm closing this issue.

Another note is that there is also a basic parser for bash scripts, which can be used if the default parser goes astray, so I'm not to worried about additional issues.
